name: Actions Mac 😎
on: [push, workflow_dispatch, pull_request]
jobs:
  build:
    name: Build Project
    runs-on: macos-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneOSX
      - uses: actions/upload-artifact@v2
        with:
          name: build-Mac
          path: build
      
  deploy:
    name: Butler Push to Itch
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-Mac
          path: build
      # Upload to Itch
      - name: Butler Push
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: mac
          ITCH_GAME: the-perfect-cake
          ITCH_USER: bellseboss
          PACKAGE: build
